### ISSUE TITLE
Can't deploy MUI icons on localhost on Windows (not sure if change is working)

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/riverscapes-gatsby#16]
@philipbaileynar and I discussed this. I was trying to follow the [instructions for using MUI icons here](https://developer.riverscapes.net/documentation/demo/#use-mui-icons) with https://github.com/Riverscapes/riverscapes-website/commit/9dc39572b54663f89a05922d70f704ec9269b045. 

On my localserver, I got this error message in the broswer:
![image](https://github.com/Riverscapes/riverscapes-website/assets/9723905/a7dd1839-9be7-487a-b9df-0a04972b22d7)

And this error message at command prompt:
```
 ERROR #gatsby-plugin-mdx_10001  PLUGIN

Failed to compile the file "C:/0_GIT/riverscapes-website/content/page/get-involved/index.mdx". Original error message:

Unexpected `ExpressionStatement` in code: only import/exports are supported

                                                                                                                                                          
 ERROR #gatsby-plugin-mdx_10001  PLUGIN

Failed to compile the file "C:/0_GIT/riverscapes-website/content/page/get-involved/index.mdx". Original error message:

Unexpected `ExpressionStatement` in code: only import/exports are supported


 ERROR #gatsby-plugin-mdx_10001  PLUGIN

Failed to compile the file "C:/0_GIT/riverscapes-website/content/page/get-involved/index.mdx". Original error message:

Unexpected `ExpressionStatement` in code: only import/exports are supported


 ERROR #98123  WEBPACK.DEVELOP

Generating development JavaScript bundle failed

C:\0_GIT\riverscapes-website\content\page\get-involved\index.mdx: Invalid left-hand side in prefix operation. (1:2)

> 1 | ---
    |   ^
  2 | title: Get Involved
  3 | description: "Get Involved"
  4 | banner: true

File: content\page\get-involved\index.mdx:1:2

failed Re-building development bundle - 2.498s                                                                                                            
ERROR in ./content/page/get-involved/index.mdx
Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
SyntaxError: C:\0_GIT\riverscapes-website\content\page\get-involved\index.mdx: Invalid left-hand side in prefix operation. (1:2)

> 1 | ---
    |   ^
  2 | title: Get Involved
  3 | description: "Get Involved"
  4 | banner: true
    at toParseError (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parse-error.ts:81:19)
    at JSXParserMixin.raise (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\tokenizer\index.ts:1487:19)
    at JSXParserMixin.checkLVal (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\lval.ts:665:12)
    at JSXParserMixin.parseUpdate (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:675:12)
    at JSXParserMixin.parseMaybeUnary (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:644:23)
    at JSXParserMixin.parseMaybeUnaryOrPrivate (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:382:14)
    at JSXParserMixin.parseExprOps (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:394:23)
    at JSXParserMixin.parseMaybeConditional (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:349:23)
    at JSXParserMixin.parseMaybeAssign (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:289:21)
    at JSXParserMixin.parseExpressionBase (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:212:23)
    at callback (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:203:39)
    at JSXParserMixin.allowInAnd (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:3134:16)
    at JSXParserMixin.parseExpression (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\expression.ts:203:17)
    at JSXParserMixin.parseStatementContent (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\statement.ts:644:23)
    at JSXParserMixin.parseStatementLike (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\statement.ts:416:17)
    at JSXParserMixin.parseModuleItem (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\statement.ts:353:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\statement.ts:1393:16)
    at JSXParserMixin.parseBlockBody (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\statement.ts:1367:10)
    at JSXParserMixin.parseProgram (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\statement.ts:212:10)
    at JSXParserMixin.parseTopLevel (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\statement.ts:194:25)
    at JSXParserMixin.parse (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\parser\index.ts:45:10)
    at parse (C:\0_GIT\riverscapes-website\node_modules\@babel\parser\src\index.ts:34:26)
    at parser (C:\0_GIT\riverscapes-website\node_modules\@babel\core\src\parser\index.ts:28:19)
    at parser.next (<anonymous>)
    at normalizeFile (C:\0_GIT\riverscapes-website\node_modules\@babel\core\src\transformation\normalize-file.ts:50:24)
    at normalizeFile.next (<anonymous>)
    at run (C:\0_GIT\riverscapes-website\node_modules\@babel\core\src\transformation\index.ts:39:36)
    at run.next (<anonymous>)
    at transform (C:\0_GIT\riverscapes-website\node_modules\@babel\core\src\transform.ts:29:20)
    at transform.next (<anonymous>)
    at step (C:\0_GIT\riverscapes-website\node_modules\gensync\index.js:261:32)
    at C:\0_GIT\riverscapes-website\node_modules\gensync\index.js:273:13
    at async.call.result.err.err (C:\0_GIT\riverscapes-website\node_modules\gensync\index.js:223:11)
 @ ./node_modules/@riverscapes/gatsby-theme/src/templates/PageTemplate.tsx?__contentFilePath=C:/0_GIT/riverscapes-website/content/page/get-involved/index.
mdx&export=default 3:0-99 227:96-115
 @ ./.cache/_this_is_virtual_fs_path_/$virtual/async-requires.js 9:147-497
 @ ./.cache/app.js 14:0-52 28:87-32:1 31:29-42 34:29-42 28:0-32:2

develop compiled with 1 error
success Writing page-data.json and slice-data.json files to public directory - 0.148s - 3/14 94.69/s
```

I tested the theory that I could just make the change and it would actually render outside my local server by pushing this commit (sorry). Based on 
![image](https://github.com/Riverscapes/riverscapes-website/assets/9723905/08c285d8-12ad-453d-be48-f979b1db7838)
It seems like I'm still doing something wrong.

**Comment by MattReimer** [comment]
Working on it. Stay tuned

**Comment by MattReimer** [comment]
This should be fixed. Also the instructions for using MUI icons have changed in the docs.

**Comment by joewheaton** [comment]
Yes @MattReimer I can confirm that these are working well in Codespaces.
